# Generated by Django 5.2.4 on 2025-12-20 05:33

import django.db.models.deletion
import django.utils.timezone
import users.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('role', models.CharField(choices=[('admin', 'Админимстратор'), ('hr', 'HR специалист'), ('candidate', 'Кандидат')], max_length=20, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('sent', 'Анкета отправлена'), ('received', 'Анкета получена'), ('accepted', 'Принят'), ('archived', 'В архиве'), ('anonymized', 'Обезличено')], db_index=True, default='new', max_length=20, verbose_name='Статус кандидата')),
                ('access_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('link_expiration', models.DateTimeField()),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('birth_place', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('citizenship', models.TextField(verbose_name='Гражданство (в т.ч. другие государства)')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('registration_address', models.CharField(max_length=255, verbose_name='Место регистрации')),
                ('residence_address', models.CharField(max_length=255, verbose_name='Место проживания')),
                ('passport_series', models.CharField(max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(max_length=255, verbose_name='Кем выдан паспорт')),
                ('passport_issued_at', models.DateField(verbose_name='Дата выдачи паспорта')),
                ('driver_license_number', models.CharField(blank=True, max_length=50, verbose_name='Водительское удостоверение №')),
                ('driver_license_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи водительского удостверения')),
                ('driver_license_categories', models.CharField(blank=True, max_length=50, verbose_name='Разрешенные категории вождения')),
                ('language', models.CharField(choices=[('en', 'Английский'), ('fr', 'Французский'), ('ru', 'Русский')], max_length=2, verbose_name='Язык общения')),
                ('foreign_languages', models.TextField(blank=True, verbose_name='Владение иностранными языками')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации с предыдущих мест работы')),
                ('military_service', models.TextField(blank=True, verbose_name='Воинская обязанность (звание, военкомат)')),
                ('disqualification', models.TextField(blank=True, verbose_name='Дисквалификация / запрет деятельности')),
                ('management_experience', models.TextField(blank=True, verbose_name='Руководство, предпринимательство, совместительство')),
                ('health_restrictions', models.TextField(blank=True, verbose_name='Заболевания и ограничения')),
                ('vacancy_source', models.CharField(blank=True, max_length=255, verbose_name='Источник информации о вакансии')),
                ('acquaintances_in_company', models.TextField(blank=True, verbose_name='Знакомые / родственники в организации')),
                ('allow_reference_check', models.BooleanField(default=False, verbose_name='Согласие на запрос рекомендаций по настоящему месту работы')),
                ('job_requirements', models.TextField(blank=True, verbose_name='Дополнительные требования к работе')),
                ('work_obstacles', models.TextField(blank=True, verbose_name='Факторы, мешающие работе')),
                ('additional_info', models.TextField(blank=True, verbose_name='Другие сведения')),
                ('salary_expectations', models.TextField(blank=True, verbose_name='Пожелания по заработной плате')),
                ('signature', models.CharField(max_length=255, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_candidates', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Организация')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='positions.position', verbose_name='Желаемая должность')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_cards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'карточка кандидата',
                'verbose_name_plural': 'Карточки кандидатов',
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name_and_location', models.CharField(max_length=255, verbose_name='Учебное заведение и местонахождение')),
                ('graduation_date', models.DateField(verbose_name='Дата окончания')),
                ('education_form', models.CharField(choices=[('full', 'Дневная'), ('evening', 'Вечерняя'), ('distance', 'Заочная')], max_length=20, verbose_name='Форма обучения')),
                ('specialty', models.CharField(max_length=255, verbose_name='Специальность')),
                ('diploma_information', models.CharField(blank=True, max_length=50, verbose_name='Информация о дипломе')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.candidate')),
            ],
            options={
                'verbose_name': 'образование кандидата',
                'verbose_name_plural': 'Образование кандидата',
            },
        ),
        migrations.CreateModel(
            name='CandidateEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата приема')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('position_and_organization', models.CharField(max_length=255, verbose_name='Должность и организация')),
                ('organization_address_and_phone', models.CharField(blank=True, max_length=255, verbose_name='Контакты организации')),
                ('manager_full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО руководителя')),
                ('dismissal_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина увольнения')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='users.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'трудовая деятельность',
                'verbose_name_plural': 'Трудовая деятельность кандидата',
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='CandidateFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100, verbose_name='Степень родства')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('occupation', models.CharField(blank=True, max_length=255, verbose_name='Род деятельности')),
                ('residence', models.CharField(blank=True, max_length=255, verbose_name='Место проживания')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='users.candidate')),
            ],
            options={
                'verbose_name': 'член семьи',
                'verbose_name_plural': 'Состав семьи кандидата',
            },
        ),
        migrations.CreateModel(
            name='CandidateVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_vacancies', to='users.candidate')),
            ],
        ),
    ]
