# Generated by Django 5.2.4 on 2025-12-20 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatevacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_vacancies', to='vacancies.vacancy'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatevacancy',
            unique_together={('candidate', 'vacancy')},
        ),
    ]
