# Generated by Django 5.2.4 on 2025-12-21 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
        ('vacancies', '0002_vacancy_code_vacancy_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidatevacancy',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='candidatevacancy',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidatevacancy',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='position',
        ),
        migrations.AddField(
            model_name='candidate',
            name='anonymization_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обезличивания'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/photos/', verbose_name='Фотография кандидата'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='vacancies.vacancy', verbose_name='Вакансия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
