# Generated by Django 5.2.4 on 2025-12-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_candidatevacancy_unique_together_and_more'),
        ('vacancies', '0003_remove_vacancy_candidates_vacancy_position_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateVacancy',
        ),
    ]
