# Generated by Django 5.2.4 on 2025-12-21 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_candidatevacancy'),
        ('vacancies', '0003_remove_vacancy_candidates_vacancy_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='allow_reference_check',
            field=models.BooleanField(blank=True, null=True, verbose_name='Согласие на запрос рекомендаций по настоящему месту работы'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='citizenship',
            field=models.TextField(blank=True, verbose_name='Гражданство (в т.ч. другие государства)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='link_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия ссылки'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='passport_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='passport_series',
            field=models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='registration_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место регистрации'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='residence_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место проживания'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='signature',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_cards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='vacancy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='vacancies.vacancy', verbose_name='Вакансия'),
            preserve_default=False,
        ),
    ]
