# Generated by Django 5.2.4 on 2025-12-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_candidate_allow_reference_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='consent_file',
            field=models.FileField(blank=True, null=True, upload_to='candidates/consents/', verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='questionnaire_file',
            field=models.FileField(blank=True, null=True, upload_to='candidates/questionnaires/', verbose_name='Анкета кандидата'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='candidates/resume/', verbose_name='Резюме'),
        ),
    ]
