# Generated by Django 5.2.4 on 2025-12-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_candidate_consent_file_candidate_questionnaire_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
    ]
