# Generated by Django 5.2.4 on 2025-12-27 19:26

import django.db.models.deletion
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_candidate_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='recommendations',
        ),
        migrations.AlterField(
            model_name='candidateeducation',
            name='graduation_date',
            field=models.PositiveIntegerField(validators=[users.validators.validate_graduation_year], verbose_name='Год окончания'),
        ),
        migrations.CreateModel(
            name='CandidateRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Рекомендация с предыдущего места работы')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'рекомендация',
                'verbose_name_plural': 'Рекомендации кандидата',
                'ordering': ('id',),
            },
        ),
    ]
