# Generated by Django 5.2.4 on 2025-12-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_candidate_recommendations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateemployment',
            options={'ordering': ('-end_date',), 'verbose_name': 'трудовая деятельность', 'verbose_name_plural': 'Трудовая деятельность кандидата'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/signatures/', verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='candidateeducation',
            name='diploma_information',
            field=models.CharField(blank=True, max_length=255, verbose_name='Информация о дипломе'),
        ),
    ]
