# Generated by Django 5.2.4 on 2025-12-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_candidateemployment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='consent_file',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='questionnaire_file',
        ),
    ]
