# Generated by Django 5.2.4 on 2025-12-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_candidate_consent_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatefamilymember',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='candidaterecommendation',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='candidaterecommendation',
            name='contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон или e-mail'),
        ),
        migrations.AddField(
            model_name='candidaterecommendation',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО рекомендателя'),
        ),
        migrations.AddField(
            model_name='candidaterecommendation',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность рекомендателя'),
        ),
        migrations.AlterField(
            model_name='candidateeducation',
            name='education_form',
            field=models.CharField(blank=True, choices=[('full', 'Дневная'), ('evening', 'Вечерняя'), ('distance', 'Заочная')], max_length=20, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='candidaterecommendation',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст рекомендации'),
        ),
    ]
