# Generated by Django 5.2.4 on 2026-02-08 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_candidate_password_candidaterefreshtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='passport_issued_at',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='passport_issued_by',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='passport_series',
        ),
        migrations.CreateModel(
            name='CandidateCitizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.TextField(blank=True, verbose_name='Гражданство (в т.ч. другие государства)')),
                ('passport_series', models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан паспорт')),
                ('passport_issued_at', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizenships', to='users.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'гражданство',
                'verbose_name_plural': 'Гражданство кандидата',
            },
        ),
    ]
