# Generated by Django 5.2.4 on 2026-02-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_candidate_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecitizenship',
            name='citizenship',
            field=models.CharField(blank=True, max_length=255, verbose_name='Гражданство (в т.ч. другие государства)'),
        ),
    ]
