# Generated by Django 5.2.4 on 2026-03-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_candidatecitizenship_citizenship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateeducation',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
