# Generated by Django 5.2.4 on 2026-03-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_candidateeducation_graduation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecitizenship',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to='candidates/passports/', verbose_name='Файл паспорта'),
        ),
        migrations.AddField(
            model_name='candidatecitizenship',
            name='residence_permit_document',
            field=models.FileField(blank=True, null=True, upload_to='candidates/residence_permits/', verbose_name='Файл вида на жительство'),
        ),
        migrations.AddField(
            model_name='candidateeducation',
            name='diploma_document',
            field=models.FileField(blank=True, null=True, upload_to='candidates/educations/', verbose_name='Файл рекомендации'),
        ),
        migrations.AddField(
            model_name='candidaterecommendation',
            name='recommendation_document',
            field=models.FileField(blank=True, null=True, upload_to='candidates/recommendations/', verbose_name='Файл рекомендации'),
        ),
        migrations.CreateModel(
            name='CandidateOtherDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='candidates/documents/', verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название документа')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_documents', to='users.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'другой документ кандидата',
                'verbose_name_plural': 'Другие окументы кандидатов',
            },
        ),
    ]
