# Generated by Django 5.2.4 on 2026-03-06 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_candidatecitizenship_passport_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateotherdocument',
            options={'verbose_name': 'другой документ кандидата', 'verbose_name_plural': 'Другие документы кандидата'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='user',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='candidateeducation',
            name='diploma_document',
            field=models.FileField(blank=True, null=True, upload_to='candidates/educations/', verbose_name='Файл диплома'),
        ),
    ]
