# Generated by Django 5.2.4 on 2025-12-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, unique=True, verbose_name='Наименование должности (русский)')),
                ('name_fr', models.CharField(max_length=255, unique=True, verbose_name='Наименование должности (французский)')),
                ('name_en', models.CharField(max_length=255, unique=True, verbose_name='Наименование должности (английский)')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'Должности',
            },
        ),
    ]
