# Generated by Django 5.2.4 on 2026-02-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Наименование должности (английский)'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Наименование должности (французский)'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Наименование должности (русский)'),
        ),
    ]
