# Generated by Django 5.2.4 on 2026-02-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_alter_position_name_en_alter_position_name_fr_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(condition=models.Q(('name_ru__isnull', False)), fields=('name_ru',), name='unique_not_null_name_ru'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(condition=models.Q(('name_fr__isnull', False)), fields=('name_fr',), name='unique_not_null_name_fr'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(condition=models.Q(('name_en__isnull', False)), fields=('name_en',), name='unique_not_null_name_en'),
        ),
    ]
