# Generated by Django 5.2.4 on 2026-02-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_position_unique_not_null_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='position',
            name='unique_not_null_name_ru',
        ),
        migrations.RemoveConstraint(
            model_name='position',
            name='unique_not_null_name_fr',
        ),
        migrations.RemoveConstraint(
            model_name='position',
            name='unique_not_null_name_en',
        ),
        migrations.AlterField(
            model_name='position',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование должности (английский)'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование должности (французский)'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование должности (русский)'),
        ),
    ]
