# Generated by Django 5.2.4 on 2026-03-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0004_remove_position_unique_not_null_name_ru_and_more'),
        ('vacancies', '0006_remove_vacancy_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
