# Generated by Django 5.2.4 on 2025-12-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование организации')),
                ('domain', models.CharField(max_length=255, verbose_name='Домен организации')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта организации')),
                ('email_password', models.BinaryField(editable=True, verbose_name='Пароль почты')),
                ('email_host', models.CharField(max_length=255, verbose_name='SMTP-сервер электронной почты')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
