# Generated by Django 5.2.4 on 2026-01-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email_port',
            field=models.PositiveIntegerField(default=465, verbose_name='Порт SMTP-сервера'),
            preserve_default=False,
        ),
    ]
