# Generated by Django 5.2.4 on 2025-12-20 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_expiration_hours', models.PositiveIntegerField(default=72, help_text='Через сколько часов ссылка становится недействительной', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок действия ссылки (часы)')),
                ('anonymization_period_days', models.PositiveIntegerField(default=365, help_text='Через сколько дней персональные данные должны быть обезличены', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок обезличивания персональных данных (дней)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
