# Generated by Django 5.2.4 on 2025-12-27 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='anonymization_period_days',
            field=models.PositiveIntegerField(blank=True, default=365, help_text='Через сколько дней персональные данные должны быть обезличены', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок обезличивания персональных данных (дней)'),
        ),
    ]
