# Generated by Django 5.2.4 on 2025-12-27 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_anonymization_period_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='anonymization_period_days',
            field=models.PositiveIntegerField(blank=True, help_text='Через сколько дней персональные данные должны быть обезличены', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок обезличивания персональных данных (дней)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='link_expiration_hours',
            field=models.PositiveIntegerField(help_text='Через сколько часов ссылка становится недействительной', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок действия ссылки (часы)'),
        ),
    ]
