# Generated by Django 5.2.4 on 2025-12-20 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование подразделения')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Уровень вложенности')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.organization', verbose_name='Организация')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='departments.department', verbose_name='Подразделение уровнем выше')),
            ],
            options={
                'verbose_name': 'подразделение',
                'verbose_name_plural': 'Подразделения',
                'unique_together': {('organization', 'parent', 'name')},
            },
        ),
    ]
