# Generated by Django 5.2.4 on 2025-12-20 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование вакансии')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], default='open', max_length=10, verbose_name='Статус')),
                ('opened_at', models.DateField(editable=False, verbose_name='Дата открытия')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('candidates', models.ManyToManyField(related_name='vacancies', through='users.CandidateVacancy', to='users.candidate', verbose_name='Кандидаты')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='departments.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
