# Generated by Django 5.2.4 on 2025-12-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='code',
            field=models.CharField(default=1, max_length=255, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='comment',
            field=models.TextField(default='Срочно', verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
