# Generated by Django 5.2.4 on 2025-12-21 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('positions', '0001_initial'),
        ('vacancies', '0002_vacancy_code_vacancy_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='candidates',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='positions.position', verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='departments.department', verbose_name='Департамент'),
            preserve_default=False,
        ),
    ]
