# Generated by Django 5.2.4 on 2025-12-21 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('positions', '0001_initial'),
        ('vacancies', '0003_remove_vacancy_candidates_vacancy_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='departments.department', verbose_name='Департамент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='positions.position', verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
