# Generated by Django 5.2.4 on 2026-03-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_vacancy_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='position',
        ),
    ]
