# Generated by Django 5.2.4 on 2026-03-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_remove_vacancy_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия'),
        ),
    ]
