# Generated by Django 5.2.4 on 2026-03-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_alter_vacancy_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Код'),
        ),
    ]
